name: CI

on:
  push:
    branches: [day1-track-trigger]  # 确保只在这个分支上运行CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
       uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install pnpm
       uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'
      - run: npm install
      - name: Run tests
        run: npm test
